development:
  adapter: postgresql
  database: waveson_development
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: waveson_test
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: waveson_production
  pool: 5
  timeout: 5000
